version: 2

builds:
  - id: certkit
    binary: certkit
    main: ./cmd/certkit/
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    overrides:
      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=clang -arch x86_64

archives:
  - id: default
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

release:
  github:
    owner: sensiblebit
    name: certkit

homebrew_casks:
  - name: certkit
    binaries:
      - certkit
    repository:
      owner: sensiblebit
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://github.com/sensiblebit/certkit
    description: A certificate management tool that ingests TLS/SSL certificates and keys, catalogs them in SQLite, and exports organized bundles.
    custom_block: |
      postflight do
        system_command "/usr/bin/xattr",
                       args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
      end
