version: 2

builds:
  - id: certkit
    binary: certkit
    main: ./cmd/certkit/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

nfpms:
  - id: certkit-deb
    package_name: certkit
    vendor: Sensiblebit
    homepage: https://github.com/sensiblebit/certkit
    maintainer: Sensiblebit <github@sensiblebit.com>
    description: >-
      A certificate management tool that ingests TLS/SSL certificates
      and private keys, catalogs them in SQLite, and exports organized bundles.
    license: MIT
    formats:
      - deb
    bindir: /usr/bin

checksum:
  name_template: checksums.txt

release:
  github:
    owner: sensiblebit
    name: certkit

homebrew_casks:
  - name: certkit
    binaries:
      - certkit
    repository:
      owner: sensiblebit
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://github.com/sensiblebit/certkit
    description: A certificate management tool that ingests TLS/SSL certificates and keys, catalogs them in SQLite, and exports organized bundles.
    custom_block: |
      postflight do
        system_command "/usr/bin/xattr",
                       args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
      end
