repos:
  # ── Git Conventions ──
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        name: no commit to main
        args: [--branch, main]

  - repo: https://github.com/sensiblebit/.github
    rev: "9bff7f460e6a6ac40de0798d7bc2f191d5143404"
    hooks:
      - id: branch-name
      - id: commit-message
      - id: goimports
      - id: go-fix
      - id: go-vet
      - id: golangci-lint
      - id: wasm
      - id: go-build
      - id: go-test
      - id: govulncheck
      - id: gendocs
      - id: prettier
      - id: vitest
      - id: wrangler-build
      - id: go-mod-update
      - id: npm-update

  # ── Markdown ──
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        args: [--config, .markdownlint.yaml]
