repos:
  - repo: https://github.com/sensiblebit/.github
    rev: "18310fd25db7cb182403c55e6495a2f9049b3078"
    hooks:
      - id: branch-name
      - id: commit-message
      - id: go-mod-update
        stages: [pre-commit]
      - id: npm-update
        stages: [pre-commit]
      - id: goimports
      - id: go-fix
      - id: prettier
      - id: markdownlint
        args: [--config, .markdownlint.yaml]
      - id: go-vet
      - id: golangci-lint
      - id: govulncheck
      - id: gendocs
      - id: wasm
      - id: go-build
      - id: wrangler-build
      - id: go-test
      - id: vitest
  - repo: local
    hooks:
      - id: golangci-lint-clean-cache
        name: golangci-lint (clean cache)
        entry: bash -c 'golangci-lint cache clean && golangci-lint run ./...'
        language: system
        pass_filenames: false
        types: [go]
