repos:
  - repo: https://github.com/sensiblebit/.github
    rev: "ddffb3a8d3bc086e7f51cec776d94d3ef21755c7"
    hooks:
      - id: branch-name
      - id: commit-message
      - id: go-mod-update
        stages: [pre-commit]
      - id: npm-update
        stages: [pre-commit]
      - id: goimports
      - id: go-fix
      - id: prettier
      - id: markdownlint
        args: [--config, .markdownlint.yaml]
      - id: go-vet
      - id: golangci-lint
      - id: govulncheck
      - id: gendocs
      - id: wasm
      - id: go-build
      - id: wrangler-build
      - id: go-test
      - id: vitest
